// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: Accounts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Balance     float64 `protobuf:"fixed64,2,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Equity      float64 `protobuf:"fixed64,3,opt,name=Equity,proto3" json:"Equity,omitempty"`
	Percentage  float64 `protobuf:"fixed64,4,opt,name=Percentage,proto3" json:"Percentage,omitempty"`
	Now         string  `protobuf:"bytes,5,opt,name=Now,proto3" json:"Now,omitempty"`
	Currency    string  `protobuf:"bytes,6,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Client      bool    `protobuf:"varint,7,opt,name=Client,proto3" json:"Client,omitempty"`
	UsedMargin  float64 `protobuf:"fixed64,8,opt,name=UsedMargin,proto3" json:"UsedMargin,omitempty"`
	MarginLimit float64 `protobuf:"fixed64,9,opt,name=MarginLimit,proto3" json:"MarginLimit,omitempty"`
	Exposure    float64 `protobuf:"fixed64,10,opt,name=Exposure,proto3" json:"Exposure,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

func (x *Account) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Account) GetNow() string {
	if x != nil {
		return x.Now
	}
	return ""
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetClient() bool {
	if x != nil {
		return x.Client
	}
	return false
}

func (x *Account) GetUsedMargin() float64 {
	if x != nil {
		return x.UsedMargin
	}
	return 0
}

func (x *Account) GetMarginLimit() float64 {
	if x != nil {
		return x.MarginLimit
	}
	return 0
}

func (x *Account) GetExposure() float64 {
	if x != nil {
		return x.Exposure
	}
	return 0
}

type AccountApiFlushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AccountApiFlushRequest) Reset() {
	*x = AccountApiFlushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiFlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiFlushRequest) ProtoMessage() {}

func (x *AccountApiFlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiFlushRequest.ProtoReflect.Descriptor instead.
func (*AccountApiFlushRequest) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{1}
}

type AccountApiFlushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AccountApiFlushResponse) Reset() {
	*x = AccountApiFlushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiFlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiFlushResponse) ProtoMessage() {}

func (x *AccountApiFlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiFlushResponse.ProtoReflect.Descriptor instead.
func (*AccountApiFlushResponse) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{2}
}

type AccountApiHistoryRequestAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	MaxSeqId  int32  `protobuf:"varint,2,opt,name=MaxSeqId,proto3" json:"MaxSeqId,omitempty"`
	RequestId int32  `protobuf:"varint,3,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	Snapshot  bool   `protobuf:"varint,4,opt,name=Snapshot,proto3" json:"Snapshot,omitempty"`
	TimeFrom  int64  `protobuf:"varint,5,opt,name=TimeFrom,proto3" json:"TimeFrom,omitempty"`
	TimeTo    int64  `protobuf:"varint,6,opt,name=TimeTo,proto3" json:"TimeTo,omitempty"`
}

func (x *AccountApiHistoryRequestAccount) Reset() {
	*x = AccountApiHistoryRequestAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiHistoryRequestAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiHistoryRequestAccount) ProtoMessage() {}

func (x *AccountApiHistoryRequestAccount) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiHistoryRequestAccount.ProtoReflect.Descriptor instead.
func (*AccountApiHistoryRequestAccount) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{3}
}

func (x *AccountApiHistoryRequestAccount) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountApiHistoryRequestAccount) GetMaxSeqId() int32 {
	if x != nil {
		return x.MaxSeqId
	}
	return 0
}

func (x *AccountApiHistoryRequestAccount) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AccountApiHistoryRequestAccount) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *AccountApiHistoryRequestAccount) GetTimeFrom() int64 {
	if x != nil {
		return x.TimeFrom
	}
	return 0
}

func (x *AccountApiHistoryRequestAccount) GetTimeTo() int64 {
	if x != nil {
		return x.TimeTo
	}
	return 0
}

type AccountApiHistoryRequestPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	MaxSeqId  int32  `protobuf:"varint,2,opt,name=MaxSeqId,proto3" json:"MaxSeqId,omitempty"`
	RequestId int32  `protobuf:"varint,3,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	Snapshot  bool   `protobuf:"varint,4,opt,name=Snapshot,proto3" json:"Snapshot,omitempty"`
	Symbol    string `protobuf:"bytes,5,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	TimeFrom  int64  `protobuf:"varint,6,opt,name=TimeFrom,proto3" json:"TimeFrom,omitempty"`
	TimeTo    int64  `protobuf:"varint,7,opt,name=TimeTo,proto3" json:"TimeTo,omitempty"`
	ValueDate string `protobuf:"bytes,8,opt,name=ValueDate,proto3" json:"ValueDate,omitempty"`
}

func (x *AccountApiHistoryRequestPosition) Reset() {
	*x = AccountApiHistoryRequestPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiHistoryRequestPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiHistoryRequestPosition) ProtoMessage() {}

func (x *AccountApiHistoryRequestPosition) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiHistoryRequestPosition.ProtoReflect.Descriptor instead.
func (*AccountApiHistoryRequestPosition) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{4}
}

func (x *AccountApiHistoryRequestPosition) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountApiHistoryRequestPosition) GetMaxSeqId() int32 {
	if x != nil {
		return x.MaxSeqId
	}
	return 0
}

func (x *AccountApiHistoryRequestPosition) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AccountApiHistoryRequestPosition) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *AccountApiHistoryRequestPosition) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AccountApiHistoryRequestPosition) GetTimeFrom() int64 {
	if x != nil {
		return x.TimeFrom
	}
	return 0
}

func (x *AccountApiHistoryRequestPosition) GetTimeTo() int64 {
	if x != nil {
		return x.TimeTo
	}
	return 0
}

func (x *AccountApiHistoryRequestPosition) GetValueDate() string {
	if x != nil {
		return x.ValueDate
	}
	return ""
}

type AccountApiHistoryResponseAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []*AccountHistory `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	RequestId int32             `protobuf:"varint,2,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *AccountApiHistoryResponseAccount) Reset() {
	*x = AccountApiHistoryResponseAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiHistoryResponseAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiHistoryResponseAccount) ProtoMessage() {}

func (x *AccountApiHistoryResponseAccount) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiHistoryResponseAccount.ProtoReflect.Descriptor instead.
func (*AccountApiHistoryResponseAccount) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{5}
}

func (x *AccountApiHistoryResponseAccount) GetData() []*AccountHistory {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AccountApiHistoryResponseAccount) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AccountApiHistoryResponsePosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []*AccountPositionHistory `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	RequestId int32                     `protobuf:"varint,2,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *AccountApiHistoryResponsePosition) Reset() {
	*x = AccountApiHistoryResponsePosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiHistoryResponsePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiHistoryResponsePosition) ProtoMessage() {}

func (x *AccountApiHistoryResponsePosition) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiHistoryResponsePosition.ProtoReflect.Descriptor instead.
func (*AccountApiHistoryResponsePosition) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{6}
}

func (x *AccountApiHistoryResponsePosition) GetData() []*AccountPositionHistory {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AccountApiHistoryResponsePosition) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AccountApiOperationRequest_AccountUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      *AccountUpdate `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	RequestId int32          `protobuf:"varint,2,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *AccountApiOperationRequest_AccountUpdate) Reset() {
	*x = AccountApiOperationRequest_AccountUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiOperationRequest_AccountUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiOperationRequest_AccountUpdate) ProtoMessage() {}

func (x *AccountApiOperationRequest_AccountUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiOperationRequest_AccountUpdate.ProtoReflect.Descriptor instead.
func (*AccountApiOperationRequest_AccountUpdate) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{7}
}

func (x *AccountApiOperationRequest_AccountUpdate) GetData() *AccountUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AccountApiOperationRequest_AccountUpdate) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AccountApiOperationRequest_PositionUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      *PositionUpdate `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	RequestId int32           `protobuf:"varint,2,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *AccountApiOperationRequest_PositionUpdate) Reset() {
	*x = AccountApiOperationRequest_PositionUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiOperationRequest_PositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiOperationRequest_PositionUpdate) ProtoMessage() {}

func (x *AccountApiOperationRequest_PositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiOperationRequest_PositionUpdate.ProtoReflect.Descriptor instead.
func (*AccountApiOperationRequest_PositionUpdate) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{8}
}

func (x *AccountApiOperationRequest_PositionUpdate) GetData() *PositionUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AccountApiOperationRequest_PositionUpdate) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AccountApiOperationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    int32           `protobuf:"varint,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	DataType     AccountDataType `protobuf:"varint,2,opt,name=DataType,proto3,enum=Pxm.Enums.AccountDataType" json:"DataType,omitempty"`
	Error        bool            `protobuf:"varint,3,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrorMessage string          `protobuf:"bytes,4,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
}

func (x *AccountApiOperationResponse) Reset() {
	*x = AccountApiOperationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiOperationResponse) ProtoMessage() {}

func (x *AccountApiOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiOperationResponse.ProtoReflect.Descriptor instead.
func (*AccountApiOperationResponse) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{9}
}

func (x *AccountApiOperationResponse) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AccountApiOperationResponse) GetDataType() AccountDataType {
	if x != nil {
		return x.DataType
	}
	return AccountDataType_AccountData
}

func (x *AccountApiOperationResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *AccountApiOperationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AccountApiResponse_Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []*Account `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	RequestId int32      `protobuf:"varint,2,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *AccountApiResponse_Account) Reset() {
	*x = AccountApiResponse_Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiResponse_Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiResponse_Account) ProtoMessage() {}

func (x *AccountApiResponse_Account) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiResponse_Account.ProtoReflect.Descriptor instead.
func (*AccountApiResponse_Account) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{10}
}

func (x *AccountApiResponse_Account) GetData() []*Account {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AccountApiResponse_Account) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AccountApiResponse_AccountExposure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []*AccountExposure `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	RequestId int32              `protobuf:"varint,2,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *AccountApiResponse_AccountExposure) Reset() {
	*x = AccountApiResponse_AccountExposure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiResponse_AccountExposure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiResponse_AccountExposure) ProtoMessage() {}

func (x *AccountApiResponse_AccountExposure) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiResponse_AccountExposure.ProtoReflect.Descriptor instead.
func (*AccountApiResponse_AccountExposure) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{11}
}

func (x *AccountApiResponse_AccountExposure) GetData() []*AccountExposure {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AccountApiResponse_AccountExposure) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AccountApiResponse_AccountPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []*AccountPosition `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	RequestId int32              `protobuf:"varint,2,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *AccountApiResponse_AccountPosition) Reset() {
	*x = AccountApiResponse_AccountPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiResponse_AccountPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiResponse_AccountPosition) ProtoMessage() {}

func (x *AccountApiResponse_AccountPosition) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiResponse_AccountPosition.ProtoReflect.Descriptor instead.
func (*AccountApiResponse_AccountPosition) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{12}
}

func (x *AccountApiResponse_AccountPosition) GetData() []*AccountPosition {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AccountApiResponse_AccountPosition) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AccountApiResponse_Reset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []*Reset `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	RequestId int32    `protobuf:"varint,2,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *AccountApiResponse_Reset) Reset() {
	*x = AccountApiResponse_Reset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiResponse_Reset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiResponse_Reset) ProtoMessage() {}

func (x *AccountApiResponse_Reset) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiResponse_Reset.ProtoReflect.Descriptor instead.
func (*AccountApiResponse_Reset) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{13}
}

func (x *AccountApiResponse_Reset) GetData() []*Reset {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AccountApiResponse_Reset) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AccountApiSubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId   int32           `protobuf:"varint,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	RequestType AccountDataType `protobuf:"varint,2,opt,name=RequestType,proto3,enum=Pxm.Enums.AccountDataType" json:"RequestType,omitempty"`
	Unsubscribe bool            `protobuf:"varint,3,opt,name=Unsubscribe,proto3" json:"Unsubscribe,omitempty"`
}

func (x *AccountApiSubscribeRequest) Reset() {
	*x = AccountApiSubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountApiSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountApiSubscribeRequest) ProtoMessage() {}

func (x *AccountApiSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountApiSubscribeRequest.ProtoReflect.Descriptor instead.
func (*AccountApiSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{14}
}

func (x *AccountApiSubscribeRequest) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AccountApiSubscribeRequest) GetRequestType() AccountDataType {
	if x != nil {
		return x.RequestType
	}
	return AccountDataType_AccountData
}

func (x *AccountApiSubscribeRequest) GetUnsubscribe() bool {
	if x != nil {
		return x.Unsubscribe
	}
	return false
}

type AccountExposure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account         string  `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Currency        string  `protobuf:"bytes,2,opt,name=Currency,proto3" json:"Currency,omitempty"`
	ExposureLimit   float64 `protobuf:"fixed64,3,opt,name=ExposureLimit,proto3" json:"ExposureLimit,omitempty"`
	CurrentExposure float64 `protobuf:"fixed64,4,opt,name=CurrentExposure,proto3" json:"CurrentExposure,omitempty"`
	ExposureRatio   float64 `protobuf:"fixed64,5,opt,name=ExposureRatio,proto3" json:"ExposureRatio,omitempty"`
}

func (x *AccountExposure) Reset() {
	*x = AccountExposure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountExposure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountExposure) ProtoMessage() {}

func (x *AccountExposure) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountExposure.ProtoReflect.Descriptor instead.
func (*AccountExposure) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{15}
}

func (x *AccountExposure) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountExposure) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountExposure) GetExposureLimit() float64 {
	if x != nil {
		return x.ExposureLimit
	}
	return 0
}

func (x *AccountExposure) GetCurrentExposure() float64 {
	if x != nil {
		return x.CurrentExposure
	}
	return 0
}

func (x *AccountExposure) GetExposureRatio() float64 {
	if x != nil {
		return x.ExposureRatio
	}
	return 0
}

type AccountHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SequenceId       int32   `protobuf:"varint,1,opt,name=SequenceId,proto3" json:"SequenceId,omitempty"`
	Time             int64   `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
	Source           string  `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`
	Total            float64 `protobuf:"fixed64,4,opt,name=Total,proto3" json:"Total,omitempty"`
	Value            float64 `protobuf:"fixed64,5,opt,name=Value,proto3" json:"Value,omitempty"`
	Comment          string  `protobuf:"bytes,6,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Name             string  `protobuf:"bytes,7,opt,name=Name,proto3" json:"Name,omitempty"`
	Balance          float64 `protobuf:"fixed64,8,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Equity           float64 `protobuf:"fixed64,9,opt,name=Equity,proto3" json:"Equity,omitempty"`
	Percentage       float64 `protobuf:"fixed64,10,opt,name=Percentage,proto3" json:"Percentage,omitempty"`
	Currency         string  `protobuf:"bytes,11,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Amount           string  `protobuf:"bytes,12,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Prev             int32   `protobuf:"varint,13,opt,name=Prev,proto3" json:"Prev,omitempty"`
	Cash             float64 `protobuf:"fixed64,14,opt,name=Cash,proto3" json:"Cash,omitempty"`
	Comment2         string  `protobuf:"bytes,15,opt,name=Comment2,proto3" json:"Comment2,omitempty"`
	Type             uint32  `protobuf:"varint,16,opt,name=Type,proto3" json:"Type,omitempty"`
	PositionSequence int32   `protobuf:"varint,17,opt,name=PositionSequence,proto3" json:"PositionSequence,omitempty"`
}

func (x *AccountHistory) Reset() {
	*x = AccountHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountHistory) ProtoMessage() {}

func (x *AccountHistory) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountHistory.ProtoReflect.Descriptor instead.
func (*AccountHistory) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{16}
}

func (x *AccountHistory) GetSequenceId() int32 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *AccountHistory) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *AccountHistory) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AccountHistory) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AccountHistory) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AccountHistory) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AccountHistory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountHistory) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountHistory) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

func (x *AccountHistory) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *AccountHistory) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountHistory) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *AccountHistory) GetPrev() int32 {
	if x != nil {
		return x.Prev
	}
	return 0
}

func (x *AccountHistory) GetCash() float64 {
	if x != nil {
		return x.Cash
	}
	return 0
}

func (x *AccountHistory) GetComment2() string {
	if x != nil {
		return x.Comment2
	}
	return ""
}

func (x *AccountHistory) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AccountHistory) GetPositionSequence() int32 {
	if x != nil {
		return x.PositionSequence
	}
	return 0
}

type AccountPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   string  `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Base      float64 `protobuf:"fixed64,2,opt,name=Base,proto3" json:"Base,omitempty"`
	Now       string  `protobuf:"bytes,3,opt,name=Now,proto3" json:"Now,omitempty"`
	Overflow  float64 `protobuf:"fixed64,4,opt,name=Overflow,proto3" json:"Overflow,omitempty"`
	OpenPnl   float64 `protobuf:"fixed64,5,opt,name=OpenPnl,proto3" json:"OpenPnl,omitempty"`
	Quote     float64 `protobuf:"fixed64,6,opt,name=Quote,proto3" json:"Quote,omitempty"`
	Symbol    string  `protobuf:"bytes,7,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Time      string  `protobuf:"bytes,8,opt,name=Time,proto3" json:"Time,omitempty"`
	ValueDate string  `protobuf:"bytes,9,opt,name=ValueDate,proto3" json:"ValueDate,omitempty"`
	Conv1     float64 `protobuf:"fixed64,10,opt,name=Conv1,proto3" json:"Conv1,omitempty"`
	Conv2     float64 `protobuf:"fixed64,11,opt,name=Conv2,proto3" json:"Conv2,omitempty"`
	Pnl       float64 `protobuf:"fixed64,12,opt,name=Pnl,proto3" json:"Pnl,omitempty"`
	Vd        string  `protobuf:"bytes,13,opt,name=Vd,proto3" json:"Vd,omitempty"`
}

func (x *AccountPosition) Reset() {
	*x = AccountPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPosition) ProtoMessage() {}

func (x *AccountPosition) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPosition.ProtoReflect.Descriptor instead.
func (*AccountPosition) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{17}
}

func (x *AccountPosition) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountPosition) GetBase() float64 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *AccountPosition) GetNow() string {
	if x != nil {
		return x.Now
	}
	return ""
}

func (x *AccountPosition) GetOverflow() float64 {
	if x != nil {
		return x.Overflow
	}
	return 0
}

func (x *AccountPosition) GetOpenPnl() float64 {
	if x != nil {
		return x.OpenPnl
	}
	return 0
}

func (x *AccountPosition) GetQuote() float64 {
	if x != nil {
		return x.Quote
	}
	return 0
}

func (x *AccountPosition) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AccountPosition) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *AccountPosition) GetValueDate() string {
	if x != nil {
		return x.ValueDate
	}
	return ""
}

func (x *AccountPosition) GetConv1() float64 {
	if x != nil {
		return x.Conv1
	}
	return 0
}

func (x *AccountPosition) GetConv2() float64 {
	if x != nil {
		return x.Conv2
	}
	return 0
}

func (x *AccountPosition) GetPnl() float64 {
	if x != nil {
		return x.Pnl
	}
	return 0
}

func (x *AccountPosition) GetVd() string {
	if x != nil {
		return x.Vd
	}
	return ""
}

type AccountPositionHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SequenceId  int32   `protobuf:"varint,1,opt,name=SequenceId,proto3" json:"SequenceId,omitempty"`
	Time        int64   `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
	Balance     float64 `protobuf:"fixed64,3,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Equity      float64 `protobuf:"fixed64,4,opt,name=Equity,proto3" json:"Equity,omitempty"`
	Percentage  float64 `protobuf:"fixed64,5,opt,name=Percentage,proto3" json:"Percentage,omitempty"`
	Mode        int32   `protobuf:"varint,6,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Comment     string  `protobuf:"bytes,7,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Account     string  `protobuf:"bytes,8,opt,name=Account,proto3" json:"Account,omitempty"`
	ValueDate   string  `protobuf:"bytes,9,opt,name=ValueDate,proto3" json:"ValueDate,omitempty"`
	Symbol      string  `protobuf:"bytes,10,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Base        float64 `protobuf:"fixed64,11,opt,name=Base,proto3" json:"Base,omitempty"`
	Quote       float64 `protobuf:"fixed64,12,opt,name=Quote,proto3" json:"Quote,omitempty"`
	Overflow    float64 `protobuf:"fixed64,13,opt,name=Overflow,proto3" json:"Overflow,omitempty"`
	OpenPnl     float64 `protobuf:"fixed64,14,opt,name=OpenPnl,proto3" json:"OpenPnl,omitempty"`
	Now         string  `protobuf:"bytes,15,opt,name=Now,proto3" json:"Now,omitempty"`
	Previous    int32   `protobuf:"varint,16,opt,name=Previous,proto3" json:"Previous,omitempty"`
	PosSequence int32   `protobuf:"varint,17,opt,name=PosSequence,proto3" json:"PosSequence,omitempty"`
	PosDelta    float64 `protobuf:"fixed64,18,opt,name=PosDelta,proto3" json:"PosDelta,omitempty"`
}

func (x *AccountPositionHistory) Reset() {
	*x = AccountPositionHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountPositionHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPositionHistory) ProtoMessage() {}

func (x *AccountPositionHistory) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPositionHistory.ProtoReflect.Descriptor instead.
func (*AccountPositionHistory) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{18}
}

func (x *AccountPositionHistory) GetSequenceId() int32 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *AccountPositionHistory) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *AccountPositionHistory) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountPositionHistory) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

func (x *AccountPositionHistory) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *AccountPositionHistory) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *AccountPositionHistory) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AccountPositionHistory) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountPositionHistory) GetValueDate() string {
	if x != nil {
		return x.ValueDate
	}
	return ""
}

func (x *AccountPositionHistory) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AccountPositionHistory) GetBase() float64 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *AccountPositionHistory) GetQuote() float64 {
	if x != nil {
		return x.Quote
	}
	return 0
}

func (x *AccountPositionHistory) GetOverflow() float64 {
	if x != nil {
		return x.Overflow
	}
	return 0
}

func (x *AccountPositionHistory) GetOpenPnl() float64 {
	if x != nil {
		return x.OpenPnl
	}
	return 0
}

func (x *AccountPositionHistory) GetNow() string {
	if x != nil {
		return x.Now
	}
	return ""
}

func (x *AccountPositionHistory) GetPrevious() int32 {
	if x != nil {
		return x.Previous
	}
	return 0
}

func (x *AccountPositionHistory) GetPosSequence() int32 {
	if x != nil {
		return x.PosSequence
	}
	return 0
}

func (x *AccountPositionHistory) GetPosDelta() float64 {
	if x != nil {
		return x.PosDelta
	}
	return 0
}

type AccountUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string  `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Source   string  `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	Amount   float64 `protobuf:"fixed64,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Comment  string  `protobuf:"bytes,4,opt,name=Comment,proto3" json:"Comment,omitempty"`
	IsDelta  bool    `protobuf:"varint,5,opt,name=IsDelta,proto3" json:"IsDelta,omitempty"`
	Currency string  `protobuf:"bytes,6,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Comment2 string  `protobuf:"bytes,7,opt,name=Comment2,proto3" json:"Comment2,omitempty"`
}

func (x *AccountUpdate) Reset() {
	*x = AccountUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountUpdate) ProtoMessage() {}

func (x *AccountUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountUpdate.ProtoReflect.Descriptor instead.
func (*AccountUpdate) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{19}
}

func (x *AccountUpdate) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountUpdate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AccountUpdate) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AccountUpdate) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AccountUpdate) GetIsDelta() bool {
	if x != nil {
		return x.IsDelta
	}
	return false
}

func (x *AccountUpdate) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountUpdate) GetComment2() string {
	if x != nil {
		return x.Comment2
	}
	return ""
}

type PositionUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account       string  `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Symbol        string  `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	ValueDate     string  `protobuf:"bytes,3,opt,name=ValueDate,proto3" json:"ValueDate,omitempty"`
	BaseDelta     float64 `protobuf:"fixed64,4,opt,name=BaseDelta,proto3" json:"BaseDelta,omitempty"`
	QuoteDelta    float64 `protobuf:"fixed64,5,opt,name=QuoteDelta,proto3" json:"QuoteDelta,omitempty"`
	OverflowDelta float64 `protobuf:"fixed64,6,opt,name=OverflowDelta,proto3" json:"OverflowDelta,omitempty"`
	Comment       string  `protobuf:"bytes,7,opt,name=Comment,proto3" json:"Comment,omitempty"`
	IsDelta       bool    `protobuf:"varint,8,opt,name=IsDelta,proto3" json:"IsDelta,omitempty"`
}

func (x *PositionUpdate) Reset() {
	*x = PositionUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionUpdate) ProtoMessage() {}

func (x *PositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionUpdate.ProtoReflect.Descriptor instead.
func (*PositionUpdate) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{20}
}

func (x *PositionUpdate) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PositionUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionUpdate) GetValueDate() string {
	if x != nil {
		return x.ValueDate
	}
	return ""
}

func (x *PositionUpdate) GetBaseDelta() float64 {
	if x != nil {
		return x.BaseDelta
	}
	return 0
}

func (x *PositionUpdate) GetQuoteDelta() float64 {
	if x != nil {
		return x.QuoteDelta
	}
	return 0
}

func (x *PositionUpdate) GetOverflowDelta() float64 {
	if x != nil {
		return x.OverflowDelta
	}
	return 0
}

func (x *PositionUpdate) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *PositionUpdate) GetIsDelta() bool {
	if x != nil {
		return x.IsDelta
	}
	return false
}

type Reset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheClean bool `protobuf:"varint,1,opt,name=CacheClean,proto3" json:"CacheClean,omitempty"`
}

func (x *Reset) Reset() {
	*x = Reset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Accounts_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reset) ProtoMessage() {}

func (x *Reset) ProtoReflect() protoreflect.Message {
	mi := &file_Accounts_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reset.ProtoReflect.Descriptor instead.
func (*Reset) Descriptor() ([]byte, []int) {
	return file_Accounts_proto_rawDescGZIP(), []int{21}
}

func (x *Reset) GetCacheClean() bool {
	if x != nil {
		return x.CacheClean
	}
	return false
}

var File_Accounts_proto protoreflect.FileDescriptor

var file_Accounts_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x50, 0x78, 0x6d, 0x2e, 0x41, 0x70, 0x69, 0x1a, 0x0e, 0x41, 0x70, 0x69, 0x45, 0x6e,
	0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x02, 0x0a, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x71, 0x75, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x45, 0x71, 0x75, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x50,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4e,
	0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4e, 0x6f, 0x77, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x64, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x55, 0x73, 0x65, 0x64, 0x4d, 0x61, 0x72, 0x67, 0x69,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x22,
	0x18, 0x0a, 0x16, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x46, 0x6c, 0x75,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc5, 0x01, 0x0a, 0x1f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x41, 0x70, 0x69, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x78, 0x53, 0x65, 0x71, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x61, 0x78, 0x53, 0x65, 0x71, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x54, 0x69, 0x6d, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x22, 0xfc, 0x01, 0x0a,
	0x20, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4d,
	0x61, 0x78, 0x53, 0x65, 0x71, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d,
	0x61, 0x78, 0x53, 0x65, 0x71, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x6d,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x54, 0x69, 0x6d,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x12, 0x1c, 0x0a,
	0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x61, 0x74, 0x65, 0x22, 0x6d, 0x0a, 0x20, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x2b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x50, 0x78, 0x6d, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x21, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x33, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x50, 0x78, 0x6d, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x22, 0x74, 0x0a, 0x28, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x69,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2a,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x50,
	0x78, 0x6d, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x29, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x50, 0x78, 0x6d, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x22, 0xad, 0x01, 0x0a, 0x1b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x36,
	0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x50, 0x78, 0x6d, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x22, 0x0a, 0x0c,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x60, 0x0a, 0x1a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x69, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50,
	0x78, 0x6d, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x22, 0x70, 0x0a, 0x22, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x69,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x50, 0x78, 0x6d, 0x2e, 0x41, 0x70, 0x69,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x22, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41,
	0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x50, 0x78, 0x6d, 0x2e, 0x41,
	0x70, 0x69, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x18, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x50, 0x78, 0x6d, 0x2e, 0x41, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x22, 0x9a, 0x01, 0x0a, 0x1a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x41, 0x70, 0x69, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x3c, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x50, 0x78, 0x6d, 0x2e, 0x45, 0x6e, 0x75,
	0x6d, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x22, 0xbd, 0x01, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x78, 0x70,
	0x6f, 0x73, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x45,
	0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0d, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x70, 0x6f,
	0x73, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x45,
	0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0d, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x52, 0x61, 0x74, 0x69,
	0x6f, 0x22, 0xc0, 0x03, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x71, 0x75, 0x69, 0x74, 0x79, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x45, 0x71, 0x75, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x0a,
	0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0a, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x50, 0x72, 0x65, 0x76, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x50, 0x72, 0x65, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x68, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x43, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x32, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x10, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x11, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x10, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x22, 0xb5, 0x02, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x6f, 0x77, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4e, 0x6f, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x76, 0x65, 0x72,
	0x66, 0x6c, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4f, 0x76, 0x65, 0x72,
	0x66, 0x6c, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x6e, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x6e, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x43, 0x6f, 0x6e, 0x76, 0x31, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x43,
	0x6f, 0x6e, 0x76, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6e, 0x76, 0x32, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x43, 0x6f, 0x6e, 0x76, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x6e,
	0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x50, 0x6e, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x56, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x56, 0x64, 0x22, 0xe8, 0x03, 0x0a,
	0x16, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x71, 0x75, 0x69, 0x74, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x45, 0x71, 0x75, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a,
	0x0a, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0a, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4d, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x42,
	0x61, 0x73, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f,
	0x77, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f,
	0x77, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x6e, 0x6c, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x6e, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x4e,
	0x6f, 0x77, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4e, 0x6f, 0x77, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x6f, 0x73,
	0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x50, 0x6f, 0x73, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x6f, 0x73, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x12, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x50,
	0x6f, 0x73, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x22, 0xc5, 0x01, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x49, 0x73, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x22,
	0xf8, 0x01, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x42, 0x61, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61,
	0x12, 0x1e, 0x0a, 0x0a, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61,
	0x12, 0x24, 0x0a, 0x0d, 0x4f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x44, 0x65, 0x6c, 0x74,
	0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x4f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f,
	0x77, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x49, 0x73, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x05, 0x52, 0x65,
	0x73, 0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x43, 0x6c, 0x65, 0x61,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x43, 0x6c,
	0x65, 0x61, 0x6e, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_Accounts_proto_rawDescOnce sync.Once
	file_Accounts_proto_rawDescData = file_Accounts_proto_rawDesc
)

func file_Accounts_proto_rawDescGZIP() []byte {
	file_Accounts_proto_rawDescOnce.Do(func() {
		file_Accounts_proto_rawDescData = protoimpl.X.CompressGZIP(file_Accounts_proto_rawDescData)
	})
	return file_Accounts_proto_rawDescData
}

var file_Accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_Accounts_proto_goTypes = []interface{}{
	(*Account)(nil),                                   // 0: Pxm.Api.Account
	(*AccountApiFlushRequest)(nil),                    // 1: Pxm.Api.AccountApiFlushRequest
	(*AccountApiFlushResponse)(nil),                   // 2: Pxm.Api.AccountApiFlushResponse
	(*AccountApiHistoryRequestAccount)(nil),           // 3: Pxm.Api.AccountApiHistoryRequestAccount
	(*AccountApiHistoryRequestPosition)(nil),          // 4: Pxm.Api.AccountApiHistoryRequestPosition
	(*AccountApiHistoryResponseAccount)(nil),          // 5: Pxm.Api.AccountApiHistoryResponseAccount
	(*AccountApiHistoryResponsePosition)(nil),         // 6: Pxm.Api.AccountApiHistoryResponsePosition
	(*AccountApiOperationRequest_AccountUpdate)(nil),  // 7: Pxm.Api.AccountApiOperationRequest_AccountUpdate
	(*AccountApiOperationRequest_PositionUpdate)(nil), // 8: Pxm.Api.AccountApiOperationRequest_PositionUpdate
	(*AccountApiOperationResponse)(nil),               // 9: Pxm.Api.AccountApiOperationResponse
	(*AccountApiResponse_Account)(nil),                // 10: Pxm.Api.AccountApiResponse_Account
	(*AccountApiResponse_AccountExposure)(nil),        // 11: Pxm.Api.AccountApiResponse_AccountExposure
	(*AccountApiResponse_AccountPosition)(nil),        // 12: Pxm.Api.AccountApiResponse_AccountPosition
	(*AccountApiResponse_Reset)(nil),                  // 13: Pxm.Api.AccountApiResponse_Reset
	(*AccountApiSubscribeRequest)(nil),                // 14: Pxm.Api.AccountApiSubscribeRequest
	(*AccountExposure)(nil),                           // 15: Pxm.Api.AccountExposure
	(*AccountHistory)(nil),                            // 16: Pxm.Api.AccountHistory
	(*AccountPosition)(nil),                           // 17: Pxm.Api.AccountPosition
	(*AccountPositionHistory)(nil),                    // 18: Pxm.Api.AccountPositionHistory
	(*AccountUpdate)(nil),                             // 19: Pxm.Api.AccountUpdate
	(*PositionUpdate)(nil),                            // 20: Pxm.Api.PositionUpdate
	(*Reset)(nil),                                     // 21: Pxm.Api.Reset
	(AccountDataType)(0),                              // 22: Pxm.Enums.AccountDataType
}
var file_Accounts_proto_depIdxs = []int32{
	16, // 0: Pxm.Api.AccountApiHistoryResponseAccount.Data:type_name -> Pxm.Api.AccountHistory
	18, // 1: Pxm.Api.AccountApiHistoryResponsePosition.Data:type_name -> Pxm.Api.AccountPositionHistory
	19, // 2: Pxm.Api.AccountApiOperationRequest_AccountUpdate.Data:type_name -> Pxm.Api.AccountUpdate
	20, // 3: Pxm.Api.AccountApiOperationRequest_PositionUpdate.Data:type_name -> Pxm.Api.PositionUpdate
	22, // 4: Pxm.Api.AccountApiOperationResponse.DataType:type_name -> Pxm.Enums.AccountDataType
	0,  // 5: Pxm.Api.AccountApiResponse_Account.Data:type_name -> Pxm.Api.Account
	15, // 6: Pxm.Api.AccountApiResponse_AccountExposure.Data:type_name -> Pxm.Api.AccountExposure
	17, // 7: Pxm.Api.AccountApiResponse_AccountPosition.Data:type_name -> Pxm.Api.AccountPosition
	21, // 8: Pxm.Api.AccountApiResponse_Reset.Data:type_name -> Pxm.Api.Reset
	22, // 9: Pxm.Api.AccountApiSubscribeRequest.RequestType:type_name -> Pxm.Enums.AccountDataType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_Accounts_proto_init() }
func file_Accounts_proto_init() {
	if File_Accounts_proto != nil {
		return
	}
	file_ApiEnums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Accounts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiFlushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiFlushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiHistoryRequestAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiHistoryRequestPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiHistoryResponseAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiHistoryResponsePosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiOperationRequest_AccountUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiOperationRequest_PositionUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiOperationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiResponse_Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiResponse_AccountExposure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiResponse_AccountPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiResponse_Reset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountApiSubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountExposure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountPositionHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Accounts_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Accounts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Accounts_proto_goTypes,
		DependencyIndexes: file_Accounts_proto_depIdxs,
		MessageInfos:      file_Accounts_proto_msgTypes,
	}.Build()
	File_Accounts_proto = out.File
	file_Accounts_proto_rawDesc = nil
	file_Accounts_proto_goTypes = nil
	file_Accounts_proto_depIdxs = nil
}
