// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: General.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueAuthenticationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password string `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *QueueAuthenticationRequest) Reset() {
	*x = QueueAuthenticationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_General_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueAuthenticationRequest) ProtoMessage() {}

func (x *QueueAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_General_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*QueueAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_General_proto_rawDescGZIP(), []int{0}
}

func (x *QueueAuthenticationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *QueueAuthenticationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type QueueAuthenticationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authenticated bool `protobuf:"varint,1,opt,name=Authenticated,proto3" json:"Authenticated,omitempty"`
}

func (x *QueueAuthenticationResponse) Reset() {
	*x = QueueAuthenticationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_General_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueAuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueAuthenticationResponse) ProtoMessage() {}

func (x *QueueAuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_General_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueAuthenticationResponse.ProtoReflect.Descriptor instead.
func (*QueueAuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_General_proto_rawDescGZIP(), []int{1}
}

func (x *QueueAuthenticationResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

type QueueErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string    `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Type    ErrorType `protobuf:"varint,2,opt,name=Type,proto3,enum=Pxm.Enums.ErrorType" json:"Type,omitempty"`
}

func (x *QueueErrorResponse) Reset() {
	*x = QueueErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_General_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueErrorResponse) ProtoMessage() {}

func (x *QueueErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_General_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueErrorResponse.ProtoReflect.Descriptor instead.
func (*QueueErrorResponse) Descriptor() ([]byte, []int) {
	return file_General_proto_rawDescGZIP(), []int{2}
}

func (x *QueueErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueueErrorResponse) GetType() ErrorType {
	if x != nil {
		return x.Type
	}
	return ErrorType_GeneralError
}

type QueuePing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId int32 `protobuf:"varint,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *QueuePing) Reset() {
	*x = QueuePing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_General_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueuePing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuePing) ProtoMessage() {}

func (x *QueuePing) ProtoReflect() protoreflect.Message {
	mi := &file_General_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuePing.ProtoReflect.Descriptor instead.
func (*QueuePing) Descriptor() ([]byte, []int) {
	return file_General_proto_rawDescGZIP(), []int{3}
}

func (x *QueuePing) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type QueuePong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId int32 `protobuf:"varint,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
}

func (x *QueuePong) Reset() {
	*x = QueuePong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_General_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueuePong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuePong) ProtoMessage() {}

func (x *QueuePong) ProtoReflect() protoreflect.Message {
	mi := &file_General_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuePong.ProtoReflect.Descriptor instead.
func (*QueuePong) Descriptor() ([]byte, []int) {
	return file_General_proto_rawDescGZIP(), []int{4}
}

func (x *QueuePong) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type QueueSessionReset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueueSessionReset) Reset() {
	*x = QueueSessionReset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_General_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueSessionReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueSessionReset) ProtoMessage() {}

func (x *QueueSessionReset) ProtoReflect() protoreflect.Message {
	mi := &file_General_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueSessionReset.ProtoReflect.Descriptor instead.
func (*QueueSessionReset) Descriptor() ([]byte, []int) {
	return file_General_proto_rawDescGZIP(), []int{5}
}

var File_General_proto protoreflect.FileDescriptor

var file_General_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x50, 0x78, 0x6d, 0x2e, 0x41, 0x70, 0x69, 0x1a, 0x0e, 0x41, 0x70, 0x69, 0x45, 0x6e, 0x75,
	0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x1a, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x43,
	0x0a, 0x1b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x64, 0x22, 0x58, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x75, 0x65, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x50, 0x78, 0x6d, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x29, 0x0a,
	0x09, 0x51, 0x75, 0x65, 0x75, 0x65, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_General_proto_rawDescOnce sync.Once
	file_General_proto_rawDescData = file_General_proto_rawDesc
)

func file_General_proto_rawDescGZIP() []byte {
	file_General_proto_rawDescOnce.Do(func() {
		file_General_proto_rawDescData = protoimpl.X.CompressGZIP(file_General_proto_rawDescData)
	})
	return file_General_proto_rawDescData
}

var file_General_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_General_proto_goTypes = []interface{}{
	(*QueueAuthenticationRequest)(nil),  // 0: Pxm.Api.QueueAuthenticationRequest
	(*QueueAuthenticationResponse)(nil), // 1: Pxm.Api.QueueAuthenticationResponse
	(*QueueErrorResponse)(nil),          // 2: Pxm.Api.QueueErrorResponse
	(*QueuePing)(nil),                   // 3: Pxm.Api.QueuePing
	(*QueuePong)(nil),                   // 4: Pxm.Api.QueuePong
	(*QueueSessionReset)(nil),           // 5: Pxm.Api.QueueSessionReset
	(ErrorType)(0),                      // 6: Pxm.Enums.ErrorType
}
var file_General_proto_depIdxs = []int32{
	6, // 0: Pxm.Api.QueueErrorResponse.Type:type_name -> Pxm.Enums.ErrorType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_General_proto_init() }
func file_General_proto_init() {
	if File_General_proto != nil {
		return
	}
	file_ApiEnums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_General_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueAuthenticationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_General_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueAuthenticationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_General_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_General_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueuePing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_General_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueuePong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_General_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueSessionReset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_General_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_General_proto_goTypes,
		DependencyIndexes: file_General_proto_depIdxs,
		MessageInfos:      file_General_proto_msgTypes,
	}.Build()
	File_General_proto = out.File
	file_General_proto_rawDesc = nil
	file_General_proto_goTypes = nil
	file_General_proto_depIdxs = nil
}
